version: "3.8"

services:
  db:
    image: docker.io/library/mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: tempdb
      MYSQL_USER: tempuser
      MYSQL_PASSWORD: temppass
    networks:
      - tempnet
    deploy:
      replicas: 1

  app:
    image: docker.io/larababic/tempconverter:dev
    environment:
      DB_USER: tempuser
      DB_PASS: temppass
      DB_HOST: db
      DB_NAME: tempdb
      STUDENT: "Lara Babić"
      COLLEGE: "Algebra Bernays University"
    networks:
      - tempnet
    ports:
      - "80:5000"
    deploy:
      replicas: 2
      placement:
        max_replicas_per_node: 1

networks:
  tempnet:
    driver: overlay